In [1]:
import numpy as np

In [6]:
np.zeros((2,2)), np.ones((2,2))

(array([[0., 0.],
        [0., 0.]]), array([[1., 1.],
        [1., 1.]]))

In [33]:
d = np.random.rand(2,2), np.ones((2,2))/4
np.minimum(np.random.rand(2,2), np.ones((2,2))/4)

array([[0.1590379 , 0.25      ],
       [0.25      , 0.16012023]])

In [34]:
d

(array([[0.1590379 , 0.39680915],
        [0.44648049, 0.16012023]]), array([[0.25, 0.25],
        [0.25, 0.25]]))

In [36]:
x = [32,3232,343,43,54,32,544,65]

In [39]:
x[1:3]

[3232, 343]